### ISSUE TITLE
Animaide only works on certain controls.

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#10]
For some reason it only seems to work on controls that have all the axes of all the transformations unlocked, if say scale is locked, even if im only trying to rotate it wont work.

**Comment by aresdevo** [comment]
I can not replicate it. It is a feature of the addon (forgot to add that to the readme) the fact that it would not affect the curves that are locked. But maybe there are situations I didn't foresee where that can malfunction. I will keep trying to replicate but so far I have not been able to.

Maybe try running Blender from the shell to see if any error shows up there

**Comment by aresdevo** [comment]
When I say it will not affect the f-curves that are lucked I mean locked on the "Graph Editor" or the "Dope Sheet", not the lock feature on the property pannel or the "N" panel.

But anyway, sorry you are having problems with the addon. Please let me know if any errors show up on the shell to be able to help you.

**Comment by aresdevo** [comment]
Ok...  I could replicate it in a very specific situation, but it is not actually a bug, it is a feature that maybe I need to make people more aware off in the readme. 

If in the main settings (the one next to the "+" and "-" buttons) the option "non-selected f-curves" 
 is unchecked, now if the only f-curve you have selected is the locked one then the slider will not do anything. The reason is that when you uncheck the "non-selected f-curves" option the slider will only affect the f-curves you have selected, but since the one you have selected is locked it will not do anything.

Let me know if this is the case.

**Comment by lucianomunoz** [comment]
i cant remember the issue, really, sorry i didnt get any notifications about you commenting.
Now im back animating in blender (uff its been a while).

**Comment by aresdevo** [comment]
No problem
