### ISSUE TITLE
-- notes -- thoughts -- suggestions maybe

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#20]
Hey Man, lovely work, honestly,  I cant live without animbot in maya and you getting so close to it in blender makes life definitelly better.
- I like what you've done with the hotkeys and piemenus, sadly with "emulate numpad" on they stop working, would be a nice add as people with laptops will generally use it, like me.
on the other hand the hotkeys and pie menus are cool, i'd love if in the dropdown to choose the type of slider the hotkeys for each one would appear next to the name (like in the rest of blender)
- coming from animbot the little mid point in the slider one the first reaction is to click and drag, but you have to click release and then move, that made me go in circles for a while not understanding how it works, it would be great if we had both work together, that you can click, drag and release where you want the slider, or click, slide and click again, i think the first one is a bit more precise mostly when you're using a pen tablet.
- It would also be great to be able to use it while on the viewport (like animbot) not just on the selected keyframes on the graph editor.
- are you thinking of implementing other sorts of animbot tools like copy paste worldspace and relationship?, 
Im doing a project for a few days more so ill be testing it more thoroughly.
that would be great.

**Comment by aresdevo** [comment]
Good suggestions. I think the problem with the Numpad has been address by @Irmitya, but I will see what I can do about the others

**Comment by aresdevo** [comment]
I just published a new version of the addon and have changed some stuff based on your suggestions.

- @Irmitya had already added a menu and taken out all the built-in shortcuts. I just added a few more commands.
- I redesigned a bit how the "slider" works to avoid confusion. I decided to abandon the concept of sliders and committed to buttons instead (because of that I changed the name of the tool). Hopefully is more intuitive now, but it doesn't address your concern of not being very precise. I'll keep working on it, I may have a solution.
- The tool now works in the 3D View too. It has a panel there. It also works on the timeline so the animTransform' mask (now called animOffset) can be created there too. The mask creation is interactive now.

Please check the [readme](https://github.com/aresdevo/animaide) to see all the things that are new in this version.

My plan is to keep adding new tools to this addon, but I have never used animbot. At Dreamworks where I work, we don't use Maya so I just know the tools we have there and the ones I used at BlueSky at one point. The closest thing I had to using animbot is atools. So if you have suggestions I'm all ears.

**Comment by aresdevo** [comment]
Hey, Just added a new revision with an option to activate the curveTools by clicking and dragging. Learn more about it in the readme (it is highlighted in the "new in this version"). Let me know what you think.
![active_on_release](https://user-images.githubusercontent.com/16739268/104990855-53de1680-59d2-11eb-80ef-e3120f5fd84d.gif)

**Comment by RiggingDojoAdmin** [comment]
Nice ! looking forward to testing it
