### ISSUE TITLE
Can't figure it out

### ISSUE THREAD

**Issue by svankirk** [aresdevo/animaide#22]
this looks like an incredibly useful tool, but I really cannot figure out how to use it. I cannot seem to get the sliders to work.  Does anyone have a tutorial other than the documentation.  I've read it, but still cannot get it to work in any way that makes sense.

For instance:  I have to press activate to create a mask and then deactivate to get the sliders to work.

**Comment by aresdevo** [comment]
Sorry I have abandoned this project. This year has been crazy. I had to deal with some personal issues but things are looking better at the moment. 

Sorry to hear you could not make it work. Maybe is because in Blender I could not make the slider work as in other applications. Instead of keeping the button pressed you need to let it go and then it will slide.

Maybe I should make a video tutorial. When I do I will let you know

**Comment by aresdevo** [comment]
I have spent a few weeks going through the code enhancing the add-on and fixing bugs. Part of the things I did was address the "sliders" design so hopefully is more intuitive now.

I just publish it and call it version 1.0. Please let me know how things work for you.
