### ISSUE TITLE
Slider evokes an error

### ISSUE THREAD

**Issue by olbap65** [aresdevo/animaide#27]
Blender 2.83

In pose mode, whenever i try to use the slider clicking in the middle circle i have the following error:

**Traceback (most recent call last):
  File "C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide-master\ops.py", line 63, in invoke
    def __del__(self):
  File "C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide-master\slider_tools.py", line 652, in invoke
    context.area.tag_redraw()
ModuleNotFoundError: No module named 'zpy'

location: <unknown location>:-1**

In line 652 it says from "module zpy import utils". I tried to replace it with "module bpy import utils" (i'm fairly new to blender and coding) and it didn't work.

Thank you for such an amazing add-on.

**Comment by Irmitya** [comment]
Obviously that wouldn't work. You're using my code. I made no efforts to "publicize" my version. I just uploaded what I'm using.  
I did that 6 months ago, I only made the "module" that's calling available 3 days ago.

**Comment by Irmitya** [comment]
zpy isn't a typo. 
https://blenderartists.org/t/zpy-various-miscellaneous-addons/1254269

**Comment by olbap65** [comment]
Sorry for reporting that as a bug, obviously was me :). I've just started using blender last weekend. I saw bpy every time in blender and i thought that would work hahaha. Again sorry.
Thank you so much for your answer!

**Comment by LuizKowalskiJr** [comment]
I have the same problem, And tryed to instal de zpy module, but when i click on the checkbox in order to activate zpy an error are reported.
The slider keep not working.

![image](https://user-images.githubusercontent.com/44177230/102505546-e486a700-4060-11eb-9bca-790682600df2.png)

**Comment by Irmitya** [comment]
@LuizKowalskiJr You did not install zpy module. 
I can easily tell by reading, what you did wrong. 

I noticed why you both are complaining about errors with my code, when you're reporting said problems "here" instead of on my page. 

- - - - - 

That tab/link at the top of the page, that says **_Pull Requests_**:
that link is similar to a comments section. It is **NOT** a part of the addon. 

It is a place for ANY random person to send the owners, changes to their code, and give them a way to update their code via community contributions. Only the owner (and people the owner approves) has the final say in whether or not to accept those changes into the official database. 

However, until the contributor/owner/owner-approved **"Revoke"** or **"Commit"** those changes, they will just sit in that page for all to see. 

Those addons displayed there are just links to "copies" on other people's github pages.  ([Here](https://github.com/aresdevo/animaide) >> [Mine](https://github.com/Irmitya/animaide))

- - - - -
It is important that you both know this about Github and BitBucket and whatever else. 
For you to know WHERE you got things from, so you know where to complain about problems with them. 
Since I believe you both didn't just browse the [forks](https://github.com/aresdevo/animaide/network/members), stumble into my version and then just brought your report here, I will assume it is because you instead used my pull request, which I bear minor responsibility, as it's like me saying it's done. As such, I updated that code to include the function rather than calling it from my module. 

- - - - 
Incidentally, how DID you both grab my stuff? The only convenient way I can think of to get it is from my page.....
I opened my page to take a look and noticed there was no Issues tab. I'm now under the impression you both got it there, couldn't find the Issues, circled back here and found it, then just reported. 
I didn't know I had to manually enable Issues/Discussion.

**Comment by olbap65** [comment]
As I said in a comment you didn’t even bother answer: I’m sorry if I did it the wrong way, at the time I downloaded the add-on it was myfirst time using GitHub and blender.

I can’t really remember but I think I wrote here because I didn’t find any other way to make it work and thought it was an issue (sorry if I thought I could comment about it under an “issue tab”

Still great add-on. Thank you and if you tell me and it is possible I can delete this post.

Have a nice day and relax!

**Comment by LuizKowalskiJr** [comment]
@aresdevo please, help us!
how we can do the slider work?

**Comment by aresdevo** [comment]
Sorry I have abandoned this project. This year has been crazy. I had to deal with some personal issues but things are looking better at the moment. 

I'm an animator, not really a programmer and this was my first attempt at coding after learning a bit of python and going through Sybren training on [Scripting for artists](https://cloud.blender.org/training/scripting-for-artists/). I just wanted to give back to the community and, as a learning experience, I wanted to add some tools to Blender that I use on my day job on other programs. @Irmitya stepped in and started improving the addon but at the same time, I could not understand my own code anymore, and solving bugs became too much for my knowledge. then 2020 happened.

@Irmitya, thank you for all the help and interest in the addon but please be more considerate with the concerns of people.

I will go through the code again and try addressing the bugs, but maybe this addon won't be a necessity anymore since somebody is adding a [similar tool in Blender](https://developer.blender.org/T81836). You can download there a build for linux and windows.

**Comment by olbap65** [comment]
Thank you aresdevo for the kind words.
I hope you have a wonderful 2021!
I’m an animator myself also and I think you both have a really good add-on !

**Comment by LuizKowalskiJr** [comment]
Nice @aresdevo. Thank you for your answer and contribution with community, even with some small bugs, your addon keep useful.
Thank you too for the links, ill check out this course and try this similar tool right now.

**Comment by aresdevo** [comment]
As Irmitya said this bug is the result of downloading his version. I have spent a few weeks going through the code enhancing the add-on and fixing bugs. Hopefully, I have addressed most of them. 

I just publish it and call it version 1.0. Please let me know how things work for you.

Thanks.
