### ISSUE TITLE
On mask create

### ISSUE THREAD

**Issue by RiggingDojoAdmin** [aresdevo/animaide#28]
This is a small thing but most of the time when using the animtransform (now activated through creating the mask) often I am wanting to edit the entire animation. If there was a setting and or default to have the mask margins auto fit to the exiting keys it would save several steps and get the tool back to the speed of use of the previous build.

Thoughts? Thank you for for all the updates and bug fixes.

**Comment by lucianomunoz** [comment]
Yes please i was fighting with this too thinking i was doing it wrong.

**Comment by aresdevo** [comment]
Just pushed a new commit addressing this concern. I added a new button called "without mask" that lets you activate anim_offset without the need for a mask. For this reason now when you delete a mask it doesn't deactivate the tool. You can add and delete a mask and still be in the session.

I called the button "without mask" instead of "activate" because the now called "with mask" activates the tool too. That way people don't think they need to press two buttons instead of just one.

In my workflow, I rarely use a tool like animOffset for the entire animation, so I usually use the mask. I thought I was streamlining the process... Sorry about that.

English is not my first language so let me know if there is a better naming convention. 

Let me know what you think

**Comment by RiggingDojoAdmin** [comment]
Thank you and don't worry, it is just two different workflows. The updates to the masks make it very fast to use but thank you for adding a without mask option!

**Comment by lucianomunoz** [comment]
wow fantastic man, thank you so much ! <3

**Comment by aresdevo** [comment]
Be aware that animOffset without the mask is only going to affect keys in your playback range, so keys on or outside the margins will not be affected. I'm fixing it, mainly the fact that keys "on" the margins will not be affected because that also affects the behavior of the masks. I'm wondering though if keys outside the range should be affected like before because in scenes with a lot of keys that might have an unnecessary cost to speed.

Was the ability to modify keys outside the range useful?

**Comment by lucianomunoz** [comment]
in my case I count on the keys out of the range being modified too, i only want them not affected when i use the mas.
I dont know what everyone else things

**Comment by aresdevo** [comment]
Fixed... now affects all the keys outside the range too. Also, when using masks, keys on the margins are affected too

**Comment by aresdevo** [comment]
Let me know if this has been addressed to close the issue

**Comment by aresdevo** [comment]
I'm assuming everything in this issue has been addressed. If you feel there is something else let me know but for now, I'm going to close it. Open it again if necessary.

**Comment by lucianomunoz** [comment]
ues this is working quite well now !, i;m currently using it a lot and have not noticed any problems :D Thank you so much!
