### ISSUE TITLE
Slider tool bug on 1.01

### ISSUE THREAD

**Issue by rayluc3d** [aresdevo/animaide#31]
Hi there,

I'm running into this error when using the new animaide sliders. Clicking the incremental boxes underneath the slider however works.
![sliderbug](https://user-images.githubusercontent.com/48029605/105928674-df6f2d00-5ffa-11eb-8355-e571fd28b333.gif)
![sliderbug2](https://user-images.githubusercontent.com/48029605/105928860-37a62f00-5ffb-11eb-974c-f3fd9562638b.gif)

Error here: 

  Traceback (most recent call last):
    File "C:\Users\raymo\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animaide-master\ui.py", line 158, in draw
      slots = animaide.slider_slots
  AttributeError: 'AnimAideScene' object has no attribute 'slider_slots'
  
  location: <unknown location>:-1

**Comment by aresdevo** [comment]
hmmm... That seems like an old file. It seems you had the old version installed before you installed this one. I would recommend deleting the add-on and installing it again.

Slider_slots have been totally removed in this version. I just checked and the word "slider_slot" doesn't appear anywhere in the code now. Besides, the error says that the problem happens in line 158 and ui.py just has 125 now. 

Since it seems you had the old version installed you might encounter issues when assigning shortcuts. The reason is that AnimAide had its own built-in shortcuts, and they might still live in your preferences. If that is the case you should go to "keymaps" in the preference window and there go to the "animation" sub-panel.

![shortcut_troubleshoot](https://user-images.githubusercontent.com/16739268/105934468-1d714e80-6005-11eb-8d45-5ad0eb287dfa.gif)

**Comment by aresdevo** [comment]
The last part about the shortcuts doesn't have anything to do with your issue, just making sure you also address what might happen in the future.

**Comment by aresdevo** [comment]
Let me know if deleting the addon and installing it again works. Just make sure non of the old files are left before you install again.

**Comment by rayluc3d** [comment]
Deleting the old addon works! Thanks for the help!

**Comment by aresdevo** [comment]
Glad I could help
