### ISSUE TITLE
Feature Request: cyclic time offset

### ISSUE THREAD

**Issue by Flavelius** [aresdevo/animaide#33]
Hi,
i was looking for an addon that would allow me to shift certain curves in time for animation cycles to allow for adjustment of character bodypart movement phases.
I found your addon which looked like it would allow this, but i didn't find that specific feature.
I posted a question about this on reddit, maybe the description there is a bit better: https://www.reddit.com/r/blender/comments/l974ae/make_fcurve_keyframes_cyclic_within_range_offset/
Do you think you could provide this with your addon?

**Comment by aresdevo** [comment]
![time_offset](https://user-images.githubusercontent.com/16739268/106497005-634d6d00-6472-11eb-8d65-e3f12ecda6dd.gif)
I think I understand what you want. In my first read, I thought maybe adding a cycle option to the time-Offset tool might do the trick for you  (the animation would repeat as you move the time). That is not actually that hard, but the curves would need to be sampled before proceeding in other to have all the keys with a similar distance. 
On the other hand, It would be interesting to see if there is a way to actually wrap the keys of the animation from the beginning to the end instead of just replacing the values of existing keys like the time-offset tool does. That would be a nice challenge.
I might try both approaches.

In the meantime, maybe baking the curve could solve your issue:
![cycle_bake](https://user-images.githubusercontent.com/16739268/106500819-23d54f80-6477-11eb-95ef-89ea18c6a659.gif)
I hope it helps.

By the way, I keep wondering how people find my addon. I know I have not done much to promote it. How did you find it?

**Comment by aresdevo** [comment]
<img width="254" alt="Screen Shot 2021-02-01 at 11 32 43 AM" src="https://user-images.githubusercontent.com/16739268/106508432-3f455800-6481-11eb-8b6c-b592a531d542.png">

Just added cycle to the time-offset tool. It should always have been there. That was an oversight. Thanks for the request.

Let me know if it works for you

**Comment by Flavelius** [comment]
Wow, that was fast. And indeed that seems to work quite well.
I found your addon while looking for animation related addons and i think it was here: https://cgcookie.com/articles/best-blender-addons-modeling-animation-sculpting-updated-for-2021#question_7
Thank you!

**Comment by aresdevo** [comment]
When I went to add the option I realized I had implemented it a while ago and had forgotten about it. So thanks for bringing that up... I only had to add it to the user interface :)

Thanks also for sharing the link.
