### ISSUE TITLE
Animaide sliders do not affect keyframes when they are Alt Selected or Row selected

### ISSUE THREAD

**Issue by rayluc3d** [aresdevo/animaide#34]
Hi there!

Seems like the sliders don't like working when they are either "Alt selected" or their entire rows are selected in the dope sheet. May have something to do with whatever blender classifies as the active selection in the animation editors? Screenshots and gif attached: 

![image](https://user-images.githubusercontent.com/48029605/106519058-94886600-648f-11eb-8170-3e8c4e232768.png)

![Animaide slider interavtion](https://user-images.githubusercontent.com/48029605/106518728-2cd21b00-648f-11eb-8230-0335e3feb77f.gif)

**Comment by aresdevo** [comment]
hmmm... This is a particular issue...

What is happening here is that when you select keys in the Dopesheet every channel gets deselected and Animaide only works on active channels. When you use box-select all the channels get selected again and of course, the addon works again.

Don't know why Blender deselect the channels when selecting keys in the dopesheet... That might actually be a Blender bug because I don't see why you would want that. To make it more strange, if you collapse the summary then the channels don't get deselected when selecting keys.

Anyway, right now you can use the "slider" in the 3D View and should work. Tools in the 3D View work a bit different because you could be working without having the dopesheet or graph-editor open (just the timeline for example) and could not see what channels are selected or not. So I made it affect all the curves in the selected object when you are in the 3D View. In the Graph Editor didn't think made much sense to work on unselected channels... I don't know.

Having said all that, I decided to treat the tools in the dopesheet the same as on the 3D View, so if you download the latest version of the addon the "sliders" in the dopesheet should work.

I would have to think if it makes sense to add that to the Graph Editor too... not sure.

Thanks for reporting this.

Let me know what you think and if the new approach works for you.

**Comment by rayluc3d** [comment]
Hey! This approach works for me, thanks for the fix!

**Comment by aresdevo** [comment]
Glad it worked.

**Comment by aresdevo** [comment]
By the way. I think it is important you know that if you select keys when the summary is collapsed (like it usually is in the timeline) the channels don't get deselected, so the tools will work in the graph editor. I thought you needed to know in case you need the graph editor larger but still want to select keys in a dopesheel like environment.
