### ISSUE TITLE
Animaide for blender 2.91 cant get it to activate

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#36]
Hey man, thanks for all the hard work i know it can be a pain to maintain several versions of the addon too, we're using 2.91 at work and sadly i cant get the addon to run.. :(

I get this message:
![image](https://user-images.githubusercontent.com/5134226/106587310-5c416000-6541-11eb-97fd-1bdd376f2b33.png)

Let me know if i can provide further info

**Comment by aresdevo** [comment]
It seems that this error comes from the addon installation. It is trying to find the addon but for some reason, it is not there.
Could you try deleting the addon in Blender preferences and installing it again?

Let me know if this works.

**Comment by aresdevo** [comment]
Sorry... None of what I said would help. Something went wrong when creating the releases in GitHub and they are giving that error now... looking for the reason it is happening.

**Comment by lucianomunoz** [comment]
thank you for looking into it, i appreciate your time a lot :), 
love the tool can barely work without it

**Comment by aresdevo** [comment]
Ok... if you download it now should work. I was trying out GitHub "release" feature and it keeps adding that error to the addon... Until I solve the issue I won't post releases, just download from the master or from the LTE branch (meant for blender 2.83)

**Comment by lucianomunoz** [comment]
alright ! thanks!

**Comment by aresdevo** [comment]
Oh... I know what the problem was... Blender doesn't like when you have dots in the name of the addon. So, for example, GitHub is adding the version number to the name like "animaide-1.0.2", and Blender disregards whatever comes after the "." so it just sees "animaide-1", but there is no such directory. Just taking the dots out of the name would have solved your issue. But because GitHub will always add the version number to the file I don't think is a good idea to use the release method.

**Comment by aresdevo** [comment]
> thank you for looking into it, i appreciate your time a lot :),
> love the tool can barely work without it

Distracted by the issue, didn't  see your comment before. Thanks a lot, i appreciate it. Knowing the tool is helpful motivates me to keep going.
