### ISSUE TITLE
Error when using on objects

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#40]
I'm getting some errors when using it on objects instead of bones :

![image](https://user-images.githubusercontent.com/5134226/107617044-170ae580-6c47-11eb-984a-b93eb12b9f7a.png)

and after that it kind of break s the addon

Also i think tools like animoffset make more sense in the viewport than in the animation editors, as you basically want to click and move the object/bone around

**Comment by aresdevo** [comment]
I have not checked on the master branch but that bug does not seem to be in the "work in progress" one. I'm almost ready to merge it to master so that bug will be fixed then. In the meantime, you could use the "work in progress" branch since it is supposed to be stable at this point.

**Comment by aresdevo** [comment]
> Also i think tools like animoffset make more sense in the viewport than in the animation editors, as you basically want to click and move the object/bone around.

The reason it needs to be in the animation editors too is because of the mask. When I put the mask button on the viewport the interactive mask creation is not mapped correctly to the animation area. But I'm actually thinking that not all the features of the addon should be in pannels. I'm evaluating if animOffset should be buttons next to the autokey in the timeline for example. That is one of the last touches I'm working on. I'm trying to add preferences to AnimAide in the addon window to let the user choose if they want animOffset in a panel or as buttons among other things.

**Comment by aresdevo** [comment]
As it is now, in the "work in progress" branch there is no mask button on the viewport for the animoffset.

**Comment by aresdevo** [comment]
Just merged the development version to master. This bug should be gone

**Comment by aresdevo** [comment]
Have not seen this, so I'm assuming it is solved
