### ISSUE TITLE
Using with a programmable keyboards

### ISSUE THREAD

**Issue by stan-sib** [aresdevo/animaide#42]
This is not the issue but I couldn't find a better place to ask. 
There is a programmable keyboard which allows you to use ascii strings for keys, so how that string should look like to use it with that kind of keyboards?
E.g. I want to put push_pull command with the smallest value to a programmable key so I could press a button on selected keyframes in graph editor and it push_pulls immediately on that smallest value. How that ascii string should look like for this case?
![изображение](https://user-images.githubusercontent.com/7447511/112609297-f640cd00-8e4d-11eb-8d5c-d08c0f9e2f00.png)

**Comment by aresdevo** [comment]
First of all, thanks a lot for your interest in the addon.
In regard to your question, what you could do is add a shortcut to that button (shortcut not only works on menu items). In case you are new to Blender, this is how you would add a shortcut:

![push_pull_shortcut](https://user-images.githubusercontent.com/16739268/112720321-d1367380-8eba-11eb-8283-0ec12df52854.gif)

After the shortcut is created you can use the key you used for the button in your programable keyboard.
The only issue when you create a shortcut on these buttons is that you don't have a way to know what shortcuts you added to them within the panel interface. In case you want to delete or modify the shortcut, you can do so by going to the "keymap" tab on the preference window:

<img width="658" alt="keymap_tab" src="https://user-images.githubusercontent.com/16739268/112720453-a39dfa00-8ebb-11eb-98b2-24da6beb5f7f.png">

You will see that whatever area you created a shortcut in there will be a "restore" button next to it. In this case "animation". If you expand it, at the bottom you will find the shortcut you just added:

<img width="658" alt="created_shortcut" src="https://user-images.githubusercontent.com/16739268/112720531-3048b800-8ebc-11eb-99b9-bdeaf9d82db8.png">

So, this is what you need for your programable keyboard, but I thought now that I've gotten this far, let me show you how you could add more shortcuts within the preference window:

As you can see, the shortcut has a command: anim.aide_push_pull, and it has a specific value of interest to you: "factor" (in this case -25). You can actually put whatever value you want there from 0 to 100, so you don't have to limit yourself to the values already in the buttons.

As you can see just below the shortcut there is an "Add new" button. That means you can add new shortcuts directly here, you just need to know the command. As you saw in the previous example the command was anim.aide_push_pull, I'll give you the list of the other commands, but honestly it is very ease to find them withing Blender. If you go to the  Blender console and type: "bpy.ops.anim.aide_" and then select autocomplete:

<img width="600" alt="autocomplete" src="https://user-images.githubusercontent.com/16739268/112720446-8ff29380-8ebb-11eb-999c-272f02ef54e5.png">

It will give you a list of all the operators Animaide has:

<img width="420" alt="list of commands" src="https://user-images.githubusercontent.com/16739268/112720999-cda4eb80-8ebe-11eb-81cb-432f24715629.png">

The operators in the console have the bpy.ops behind them, but for the shortcuts you ignore that. For example the command for "Ease" would be: anim.aide_ease. Once you put the command on the shortcut setting all the extra information like "factor" will show up so you can modify it.

Well... I hope it wasn't too confusing. You don't need all this information but I thought could be helpful to you.

By the way, on the image you posted, I see you still have the "info" panel up. I put it there because I added some new way of working I thought it was important for people to know, but it is useless after you read it. In case you didn't see it on the read-me, you can hide that panel by going to the addon preference in the preference window:

![preferences](https://user-images.githubusercontent.com/16739268/112721347-8f103080-8ec0-11eb-886d-511da3629081.jpg)

You can un-check the "info panel" at the bottom.

Sorry for all this information. I hope it didn't scare you :P

Let me know if it works for you

**Comment by stan-sib** [comment]
Thanks! I didn't know that I can set hotkeys on that values, thought that it possible to set on a tool only) This is even better so as I can set same tools on same hotkeys let's say for Blender and Maya etc.  It works great! But I am curious anyway how full command should look like. I ve tried - anim.aide_push_pull(slope=1, factor=0.25)  but it didn't work

**Comment by aresdevo** [comment]
Seems like the shortcut worked for you? but the last question confused me. Are you saying you added a new shortcut within the preference window adding the push_pull command directly and didn't work?... If that is what you mean maybe I forgot to tell you an important detail...

When you add one of the animTools operators commands to a shortcut the default mode is the one used in the form of a slider. So maybe it is not that it didn't work for you, but just that when you were using the shortcut you needed to move the mouse to activate it (as it happens on the panel when you activate the main big button):

<img width="409" alt="push_pull default" src="https://user-images.githubusercontent.com/16739268/112735037-c30e4480-8f06-11eb-83a4-4d729f3b45ed.png">

as you can see, there is an option to the right I didn't talk about called "op_context", or as it is in the image "op_con..." (the name is not complete on the image because the preference window was too small).  The default for that option is "INVOKE_DEFAULT"  that is the way the tool typically works using the mouse as a slider, but if you change it to
"EXEC_DEFAULT" then works as the small buttons on the interface:

<img width="409" alt="push_pull execute" src="https://user-images.githubusercontent.com/16739268/112735167-9a3a7f00-8f07-11eb-8db9-1e360d080eb9.png">

I know it is not intuitive as it is right now because you would need to know the "EXEC_DEFAULT" option to be able to change it. I will correct that so when you add a shortcut that is a pop-up menu that lets you choose between two options.

Be aware that I also selected the "repeat" option. What that does is repeat the command when you keep the shortcut key pressed.

By the way, in case you are wondering, the "slope" option just affects the anim_aide_ease and anim.aide_ease_to_ease operators. Maybe I should try to take it out of the other operators. What that option does is make the ease curve more or less steep.

Anyway... I hope this helps.

**Comment by aresdevo** [comment]
Ok... based on this conversation I updated the addon with simpler options for the shortcut window:

<img width="459" alt="simpler options" src="https://user-images.githubusercontent.com/16739268/112737960-f0b1b880-8f1b-11eb-8ecb-c0373bf6ee96.png">

I remove the "slope" option since it is mainly an internal thing I need but the user has not much use for it. I also changed the "op_context" option to "Mode" and used a pop-up menu for the options. Also, instead of the cryptic term "INVOKE_DEFAULT" I used "Slider" and for "EXEC_DEFAULT" I used "Steps". Much more intuitive I think.

Anyway, download the addon again to get this new version. You might need to delete the shortcuts you created and create them again to see the changes.

If for some reason the addon is giving you any problem after the update you might need to do a clean install (remove the addon and install it again)

to remove it, use the "remove" button on the addon preferences:

![preferences](https://user-images.githubusercontent.com/16739268/112738055-c01e4e80-8f1c-11eb-988c-c6bfcb4c0e63.jpg)

Anyway, thanks for the question, it led to a better alternative.

**Comment by aresdevo** [comment]
I need to work now on all the other Animaide operators aside from curveTools. They need options added to better create shortcuts.

**Comment by stan-sib** [comment]
no no no) Hotkeys work fine!) 
I meant that I have got options on keyboard  to put hotkeys there as well as direct commands
![2021-03-28_10-46-54](https://user-images.githubusercontent.com/7447511/112741898-b4ca3200-8fb3-11eb-9bfe-a49e9a8def4d.png)
I have tried to put direct command like anim.aide_push_pull(slope=1, factor=0.25 there and it didn't work in graph editor window
I just wanted to figure out just for myself how it should works directly, without hotkeys )

**Comment by aresdevo** [comment]
hmmm... I see. Glad the shortcuts helped then.
