### ISSUE TITLE
Repo Suggestion: Make releases instead of archives.

### ISSUE THREAD

**Issue by OlafHaag** [aresdevo/animaide#48]
You aim to provide different versions of the add-on (LTS and latest).
Currently, to get different versions, you'd have to scroll through the README until you reach the download links, or switch branches and download the repo.

I believe it would be easier for the user and yourself to create releases using Github actions. This would also provide access to previous versions without much hassle.

**Comment by aresdevo** [comment]
Thanks for the suggestion. 

I actually had that at one point but people started reporting that the add-on was not working. I could not figure out what it was because it was working at my end. It turns out that Blender got confused when the name of the addon had a "." in it, and because versions are supposed to be named in this format: name.# The file people were downloading had a "." in the file name. I think the issue is that Blender is expecting a folder name without an extension or a python file with the py extension. But in this case, it was finding a number after the dot instead of  "py".
I then tried naming the versions without dots for example "animaide_LTS". But the IDE I use to code got all confused when accessing GitHub, it thought "animaide_LTS" was another master branch instead of just a version. I could not solve the conundrum at that time so I decided to stop trying.

But... If you have a solution for me I would be very grateful.

**Comment by OlafHaag** [comment]
That sounds indeed frustrating. I'm sorry you had to go through that. It's good to know that Blender trips up if there's a dot in the name.
I just started Blender add-on development and set up my repo a bit different. But basically when I create a release I upload a zip  archive with a custom name, so users will have to download that file instead of the source code archive that is named after the tag (which follows semantic versioning with dots and all that).

I set the Github action to run any time a tag was pushed. You can set up different actions to run for different branches. That would allow you to name the artifact differently for the LTS releases.
Here's my workflow:
https://github.com/OlafHaag/AvatarComponentCombinations/blob/main/.github/workflows/publish-add-on-release.yml
My add-on code resides in a subfolder, so I can have documentation and examples in the repo that won't be part of the installed files. The downside to my folder structure is that users can't just download the source and install it. They need to get the release.
But in your case it's just the root path ('.') which would need to be zipped. There's also a workaround to get the pushed tag, if you want to convert it to some format as part of the filename that Blender understands.

I hope this helps!

**Comment by aresdevo** [comment]
Thanks... I'm new to Github so that info is appreciated.

**Comment by aresdevo** [comment]
@OlafHaag, I have been distracted by my life as animator so I have not been doing much coding for a while. What you have as a workflow seems to be better than mine. I'm not really a coder so I'm not that familiar with what I saw there. I might ask you some questions... is that ok?

By the way, I have seen other addons that do the versioning thing and they don't seem to have the issue with the dot I had... I need to investigate that because having versions would be amazing.

**Comment by OlafHaag** [comment]
Sure, you can ask! If I can find the time myself, I might even be able to help with a pull request.

**Comment by aresdevo** [comment]
Thanks, that would be awesome!

In regard to how to set up Github for the versioning thing, I'm using pyCharm and found out that it can do all the heavy lifting for me. I can add tags for releases through pyCharm and it works like a "charm" :P. The thing it keeps happening is that because of the versioning, the addon downloads with dots on its name and Blender doesn't recognize it. For example, the tag I created for a version was v1.0.3, so the name of the file downloaded is animaide1.0.3.py. Blender things is looking for a file named animaide1 (it thinks everything after the first dot is an extension I guess). My solution for the moment was just adding "_" instead of "." to the version. The tag as it is now is v1_0_3. Have you experienced this issue?... if so, how did you solve it?

**Comment by OlafHaag** [comment]
I did not yet experience the issue myself, but I saw another add-on (Daniel Bystedt's Blender Baker) which also used underscores for the version in the filel name.

**Comment by aresdevo** [comment]
Hey @OlafHaag  ... I follow your advice, I have releases now. Thanks for the suggestion, It is way better this way.

**Comment by OlafHaag** [comment]
I'm glad it worked out!
