### ISSUE TITLE
Anim Transform slow when using Pose mode with a lot of keyframes

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#5]
It updates fine when using an object with sampled keyframes but if for example, you 're using a rig and you sample all the keyframes for all the bones, it's slows down Blender when trying to rotate just one of the bones. 

I edited the `magnet.py > animation_transform` function to only run on bone's fcurves if it's selected or its parent or child is selected: 
```
    # When posing, limit affected bones to selected and nearby
    if fcurve.data_path.startswith(('pose.bones', 'bones[')):
        name = fcurve.data_path.split('[\"')[1].split('\"]')[0]
        bone = obj.data.bones.get(name)
        if bone is None:
            return
        if not bone.select:
            for b in {bone.parent, *bone.children}:
                if b and b.select:
                    break
            else:
                return
```

It runs fast with this but there's still a lag when using a mask and I don't know why

**Comment by aresdevo** [comment]
Thanks so much for reporting this and trying to find a solution. I remember there was a reason I had to look through all the bones, but I'm sure whatever the reason was, it must be a better way. I'll take a look. By the way, I know I need to add more comments on the code to make life easier for others (and myself), so thanks for going through it and finding your way around and sorry for no been more thoughtful.

**Comment by aresdevo** [comment]
Hmmmm... Checking the code I realized I got so distracted with the sliders that forgot to make Anim-Transform compatible with Armatures. I'll make sure to address that. Thanks again

**Comment by Irmitya** [comment]
Cool, hope it works out. 
I've wanted motion editor for some time but gave up because no one seemed to either understand or want it and I gave up on doing it myself _(and did something else instead)_.

I focused in on the animbot's feature list _(video, because the site doesn't display the page anymore)_ and saw it actually had that.  I thought SFM was the ONLY thing around that had anything like this but I just never noticed it in animbot's feature list. 

As such, I'm looking forward to migrating it into my process more.

**Comment by aresdevo** [comment]
I never got the chance to use "animbot", I only used it's predecessor "aTools" and similar tools they have implemented in different studios I've worked at. 

Anim-Transform seems to be working faster with bones now. The code you supplied helped me a lot. The mask will always be slower because it needs to evaluate the values of the f-curve in relationship to the mask curve but hopefully works a bit better now. You can download a new version of the add-on now for testing, and please let me know how it works for you.

**Comment by aresdevo** [comment]
I didn't know there was something similar to "Anim-Transform" in "AnimBot". The inspiration actually came from a native option in 3DMax that would let you do the same but without the mask (At least when I used to use it a long time ago). The mask was inspired by a tool they have at Dreamworks.

**Comment by Irmitya** [comment]
in magnet.py, you use this code:
```
                if not bone.select:
                    for b in {bone.parent, *bone.children}:
                        # if b and not b.select:
                        if b:
                            animation_transform(obj, fcurve)
                else:
                    animation_transform(obj, fcurve)
```
The only thing I'm gathering from this is if a bone isn't selected, then run transform for every parent and child it has.  
So if a bone isn't selected, it will only "NOT" run if it doesn't have a parent or any children. 

The equivalent (that would run less) would be:
```
if (bone.select or bone.parent or bone.children):
    animation_transform(obj, fcurve)
```

I'm under the impression that you did it this way in an attempt to get it to work with IK. 
If that's the case, I modified it to only run on un-selected bones if they're in an IK chain: 

```

def anim_transform_handlers(scene):
    # ...
        # ...
        fcurves = obj_anim.action.fcurves
        ikbones = set()

        if obj.pose:
            for bone in obj.pose.bones:
                if bone.bone.select:
                    for b in get_ik_chain(bone):
                        ikbones.add(b.name)
        # ...
            # ...
                # ...

                if bone.select or bone_name in ikbones:
                    animation_transform(obj, fcurve)

def get_ik_chain(bone):
    "Returns a list of parents to the bone, if it's IK chain reaches them"
    parents = list()
    if not (bone.parent):
        return parents
    maxlen = len(bone.parent_recursive)

    def scan(constraint):
        # Note @you: parents isn't being re-declared as a variable, so don't have to declare it as nonlocal
        if (constraint.type in ('IK', 'SPLINE_IK')):
            count = constraint.chain_count
            if (count == 0 or count > maxlen):
                parents.extend(bone.parent_recursive)
            else:
                if getattr(constraint, 'use_tail', None):
                    chain_range = count - 1
                else:
                    chain_range = count
                for chain in range(chain_range):
                    parents.append(bone.parent_recursive[chain])

    for constraint in bone.constraints:
        scan(constraint)

    parents_sorted = list()
    if parents:
        for parent in bone.parent_recursive:
            if parent in parents:
                parents_sorted.append(parent)

    return parents_sorted
```

**Comment by aresdevo** [comment]
Man!... You are giving me a master class!! :) I bet you realize by now that I'm a newbie at this. you just compressed that block I added to just two lines!

Actually, that was just adapting the code you gave me to also solve the Auto-IK problem. For efficiency, I wanted to operate only on the selected bones but realized that Auto-IK affects the values of the chain. I knew the approach I used could be wasteful because it doesn't test to find an end to the affected chain, but I needed more knowledge to find out how.

I need to read several times your code to fully understand what is going on there, but I'm wondering if I really need to check if there is an IK constraint. The way IK constraints work, the bones that are part of it will not have any keys in them, just the bone the chain is constrained to. Auto-IK, on the other hand, would affect bones that are animated by hand.

I thought that maybe this code you sent me could have the answer to find where the Auto-IK would end its effect on the chain, but I see you rely on the information that is on the constraint modifier itself.

Thanks so much for all your help.

**Comment by lucianomunoz** [comment]
ay yeah its called "transform all" its also in aTools, its one of the last buttons from left to right, in atools the icon is a set of arrows that points everywhere in animbot is this one called global offset http://www.animbot.ca/tooltips/#global_offset

**Comment by aresdevo** [comment]
Oh... Thanks Luciano... great link

**Comment by aresdevo** [comment]
seeing that I realize I'm very bad at choosing names for the tools :P

**Comment by Irmitya** [comment]
> I need to read several times your code to fully understand what is going on there, but I'm wondering if I really need to check if there is an IK constraint. The way IK constraints work, the bones that are part of it will not have any keys in them, just the bone the chain is constrained to. Auto-IK, on the other hand, would affect bones that are animated by hand.

An IK constraint with a length of 0 means to extend to infinity and beyond. 
Any other length means to extend X amount of times. 

The only difference between AutoIK and a regular IK constraint is that it has some internal system property that hides it from the constraints panel. 
For example if you have a chain and you move the first bone (IE the pelvis), and then the tail bones (head/feet/hand/tail) all stick to their tips, what's happening here is an IK constraint was placed on all those bones _(with an empty target at their tail's position)_. 

What's happening with the wheel thing where you change the length of the AutoIK chain is basically just a function in the modal Transform operator, that changes the constraint's chain length. 

Generally when someone add an IK constraint, they then add a target. That target is optional.  
The constraint without a target is what the regular auto-ik is, and the constraint with an object placed at the tips is the constraint when moving the base/pelvis bone.

- - - 

So, the reason bones in an IK chain don't have keys and why what I do in the code works, is that when you use a target, you're not selecting a bone connected to any of the bones in the chain. 
If you were, it's either not an IK controller or you have a cycle redundancy loop issue and will have bigger problems than manipulating a bunch of keyframes.

(The bone that contains an IK constraint without a target essentially functions as the target, and only results in rotating it and it's recursive parents)

**Comment by Irmitya** [comment]
> ay yeah its called "transform all" its also in aTools, its one of the last buttons from left to right, in atools the icon is a set of arrows that points everywhere in animbot is this one called global offset http://www.animbot.ca/tooltips/#global_offset

I had looked for this page. I saw it nowhere.....it's on the Help Page
