### ISSUE TITLE
Anim Transform: Mask slow and randomly applies changes

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#6]
When using a mask, Blender noticeably lags far greater than when affecting ALL the keyframes _(without a mask)_.
However more importantly it will randomly apply the current transformed pose instead of cancel it, when you cancel the transform operator.

[Video example](https://streamable.com/aphwc)
In the video, every time I move/rotate the cube, I right-click to cancel it, and sometimes the pose cancels like it's supposed to and sometimes it keeps the pose, applying the change.

**Comment by aresdevo** [comment]
Thanks so much for reporting that. I will take a look

**Comment by aresdevo** [comment]
This one is breaking my brain. I have not been able to fix it. At least I found a way to always reproduce it so it's not random. If you cancel Anim-Transform while the tool is still refreshing (either because you are still moving the mouse or Blender is lagging) then it applies the value. I realized that if you undo the mask would disappear but the buttons would stay useless in the panel. At least I could fix that last bug.
