### ISSUE TITLE
Request: Choose the panel category for all view3D panels

### ISSUE THREAD

**Issue by felipetorrents** [aresdevo/animaide#75]
At the moment the only panel that shows up in the viewport is 'ANIMAIDE_PT_curve_tools_3d'. It would be great to have a string input in the preferences to customize it's location. Thank you!

**Comment by aresdevo** [comment]
hmmm... interesting.

The reason only those tools appear in the 3D view is that the other ones are very specific to the keys or curves. In fact, the curveTools that are there are the ones you can use without selecting keys because can be confusing if somebody uses them without seeing the keys. 

I see how some people could have a workflow where they select keys without expanding the animation editor (although I thought you would want to see the effect on the graph editor when you have multiple keys selected). My solution for that was to give you the option to put some tools on the header of the animation editor (Graph Editor, Dope Sheet).  I didn't include the curveTools because the strange slider I created was not working on the header, but you can still select the curveTools on the menu in the animation editors header and even assign shortcuts to them.

Could you elaborate on how you use the tool so I understand better where you are coming from?

**Comment by felipetorrents** [comment]
Sorry I wasn't very clear before. I understand the context difference of this tools and the reason of my suggestion is merely UI decluttering. Specifically when there are tons of addons enabled.

I've been combining some animation addons into a single 'Animation' panel, e.g.  Commotion, Animaide, Animation Layers, Dynamic Parent, Global Transform, Autorig-pro and Animax. 

They are quite a lot and I personally like it better in a single panel than in a different workspace. I'm a generalist and I have to switch to other roles all the time. In the mean time I manually change the script's panel category but I also managed to implement the example bellow into 'Commotion'.

The result is a string input at the addon preferences for panel category. You probably know a better way. I'm a noob with python btw.
https://blenderartists.org/t/fixing-create-hole-addon/1159847/5

**Comment by aresdevo** [comment]
Oh!... I understand your concern now. That is something I actually find lacking in Blender, a way to organize or hide some addons. That addon is very interesting. Great find!
