### ISSUE TITLE
this error is happening when i try to shoot the mask option

### ISSUE THREAD

**Issue by LeozinhoO12** [aresdevo/animaide#82]
Python: Traceback (most recent call last):
  File "C:\Users\megag\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\animaide-master\anim_offset\ops.py", line 311, in modal
    scene.frame_current = (end + start)/2
TypeError: bpy_struct: item.attr = val: Scene.frame_current expected an int type, not float

**Comment by abrasic** [comment]
Hi,

The issue is caused because, as of blender 3.1, Python was upgraded to 3.10, in which this version no longer allows implicit conversion between `float`s and `int`s. [More info here](https://wiki.blender.org/wiki/Reference/Release_Notes/3.1/Python_API)

The way to solve this issue is instead explicitly converting the ints and floats yourself, luckily the fix is very simple;

Go to `%AppData%\Roaming\Blender Foundation\Blender\3.2\scripts\addons\animaide-master\anim_offset\ops.py` 
Then in line 311, find this:

```Python
scene.frame_current = (end + start)/2
```
and change it to this:
```Python
scene.frame_current = int((end + start)/2)
```

Hopefully this helps
