### ISSUE TITLE
Make AnimOffset header color available in the addon's preferences

### ISSUE THREAD

**Issue by ehabcharek** [aresdevo/animaide#83]
Hi, first of all I want to say I love this addon, and I honestly can't work without it. I have no complaints!
I would just like to request the ability to change the header color in the addon's preferences. The current color works great with the default theme but it might not fit super well with user made themes
I noticed it overwrites the theme's color temporarily, so there's no way to edit that color unless you edit the code, which isn't that hard to be perfectly honest, but it's less user accessible

**Comment by aresdevo** [comment]
Thanks for the suggestion. that should be a simple one.

**Comment by aresdevo** [comment]
I just added this release [(Version 1.0.38.35)](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_35) addressesing this suggestion. The way I decided to implement is by just using the theme selection color and altering it a bit so it is not exactly the same. 

When testing it's better to restart Blender after changing the theme because animOffset uses the last saved theme to return to after you turn it off.

Let me know if it works for you.

**Comment by ehabcharek** [comment]
Thank you for considering my suggestion. That is a very interesting approach! I like the idea
altho personally I would use the preview range color of the dope sheet and adjust that instead, as I feel those colors are more connected. Regardless I really like the idea!
I did have an issue in line 426 of the ops.bpy file, where the function still had 4 values for RGBA between the parenthesis. Deleting them fixed the error

**Comment by aresdevo** [comment]
There is a new version [1.0.38.36](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_36) that uses the "preview range" color instead. I also addressed the small bug when using the mask icon to enable AnimOffset. Thanks for the suggestion.

**Comment by ehabcharek** [comment]
awesome, than you for the update!
this works better than what I asked for!
