### ISSUE TITLE
Getting this Error everytime I try to create an AnimOffset Mask

### ISSUE THREAD

**Issue by arthurdeszjr** [aresdevo/animaide#85]
I'm using Blender 3.3, It happens everytime I click on the animOffset button in the Dope Sheet Editor, It throws me this error straight on click.
![image](https://user-images.githubusercontent.com/11486484/200871816-4d6ffbd3-f6eb-4a58-ba87-3ed69a4563b7.png)

**Comment by aresdevo** [comment]
Sorry for the delay. I have not been actively working on the addon. There is a new [release](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_32) that should fix this

**Comment by arthurdeszjr** [comment]
After the last update the error is gone, but my object remains locked for alterations while I use the mask (even after I press right click to exit edit mask mode)


https://user-images.githubusercontent.com/11486484/201230635-e5e2a5cf-0aec-407c-b8bb-0008d9c15450.mp4

**Comment by aresdevo** [comment]
What I see in the video is what the addon is designed to do: Only keys inside the mask would be affected. In the beginning, because there is no mask, both keys are affected. Then you create a mask but the keys are outside of it so none are affected. Finally, you add blend margins to the mask but leave the keys at the end of the margin where the blending value would be zero, so no keys are affected. 

Masks are meant to be used on animations with several keys so you can isolate the ones you want to influence. The blend margins are meant to gradually decrease the influence of the keys in that range.

Sorry if it is confusing. Let me know if you got the idea or if I missed something.

**Comment by aresdevo** [comment]
by the way, there is a new release that fix another unrelated bug

**Comment by arthurdeszjr** [comment]
Thanks a lot!
